### ISSUE TITLE
How it will be different from Corona Kavach app

### ISSUE THREAD

**Issue by harshitsilly** [Corona-Trace/mobile-app#20]
https://play.google.com/store/apps/details?id=com.cosafe.android

**Comment by SAGARSURI** [comment]
It's different coz the application which you linked above has been removed from the play store. 
The reason being(maybe):
1) Provided wrong information or the source of information was not official.
2) Took user's data in a non-secure way.

**Comment by harshitsilly** [comment]
> It's different coz the application which you linked above has been removed from the play store.
> The reason being(maybe):
> 
> 1. Provided wrong information or the source of information was not official.
> 2. Took user's data in a non-secure way.

the app was built by Niti ayog and its under beta... they are working on production release..
Other thing is that this app requires mass adoption... do you have thought about the marketing aspects

**Comment by oianmol** [comment]
@harshitsilly Please post the concerns in the slack channel. Thanks!
