### ISSUE TITLE
Don't set suggestions instead add to them.

### ISSUE THREAD

**Issue by anmolvermamm** [Corona-Trace/mobile-app#34]
https://github.com/Corona-Trace/mobile-app/blob/41754a61943cd48f05fd70236116896f237e14f8/lib/ui/notifications/blocs/ct_notification_bloc.dart#L43

 yield state.rebuild((b) => b
      ..loading = false
      ..suggestions = notifications.data.toList(growable: false)
      ..pageNo = state.pageNo + 1);

**Comment by oianmol** [comment]
@matthiasbruns can you fix this ?

**Comment by SAGARSURI** [comment]
Is it related to DEV-104? @anmolvermamm

**Comment by oianmol** [comment]
107 @SAGARSURI

**Comment by oianmol** [comment]
@SAGARSURI 
  yield state.rebuild((b) => b
      ..loading = false
      ..suggestions.addAll(notifications.data)
      ..pageNo = state.pageNo + 1);
should this help ?

**Comment by oianmol** [comment]
@SAGARSURI can you review this PR for the fix ?
